#!/bin/sh /etc/rc.common

START=95
PROG=/usr/bin/helloworld


start_instance() {
	local cfg="$1"
	local duration
	local enabled

	config_get_bool enabled "$cfg" 'enabled' 0
	config_get duration "$cfg" 'duration' 0

	[ $enabled -gt 0 ] || return 1
	# Usually, procd should be used for services running in the background. See example3.
	service_start $PROG $duration
}

stop_instance() {
	local cfg="$1"
	# Nothing to do
}

start_service() {
	config_load 'helloworld'
	config_foreach start_instance 'helloworld'
}

# This is not neccessary here,
# but we include it for the sake of the example
stop_service() {
	config_load 'helloworld'
	config_foreach stop_instance 'helloworld'
}
